# Generated by Django 6.0.2 on 2026-02-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0003_student_teacher_course_student_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student',
        ),
    ]
