# Generated by Django 5.0.2 on 2026-03-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0004_rename_name_student_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
